# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: redelk-pipeline
  path.config: "/usr/share/logstash/redelk-main/conf.d"
  pipeline.ecs_compatibility: v1